#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 0
bspc config window_gap 7
bspc config split_ratio 0
bspc config border_width 0
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
feh --bg-fill ~/.config/wallpaper/hackthebox.jpg
picom --experimental-backends &
~/.config/polybar/./launch.sh
vmware-user-suid-wrapper
